CREATE TABLE `llx_diagnosi_digitale` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `entity` int(11) DEFAULT 1,
  `fk_projet` int(11) DEFAULT NULL,
  `fk_societe` int(11) DEFAULT NULL,
  `azienda_nome` varchar(255) DEFAULT NULL,
  `azienda_ragione_sociale` varchar(255) DEFAULT NULL,
  `n_dipendenti` int(11) DEFAULT NULL,
  `fatturato_annuo` double(24,8) DEFAULT NULL,
  `ex_ante_or_ex_post` BOOLEAN COMMENT DEFAULT 0 'EX-ANTE o EX-POST',
  `data_inizio_intervento` date DEFAULT NULL COMMENT 'Data di inizio intervento',
  `data_fine_intervento` date DEFAULT NULL COMMENT 'Data di fine intervento',
  `data_compilazione` date DEFAULT NULL COMMENT 'Data della Diagnosi Digitale',
  `digital_workplace_numero` INT COMMENT  'A. Digital Workplace Numero',
  `digital_workplace` DECIMAL(10, 2) COMMENT 'A. Digital Workplace Contributo',
  `digital_comm_engag`DECIMAL(10, 2) COMMENT 'B. Digital Commerce & Engagement Contributo',
  `digital_comm_engag`DECIMAL(10, 2) COMMENT 'B. Digital Commerce & Engagement Contributo',
  `cloud_comp_app_server`DECIMAL(10, 2) COMMENT 'C.1 Cloud Computing - Application Server Contributo',
  `cloud_comp_db_server`DECIMAL(10, 2) COMMENT 'C.2 Cloud Computing - Database Server Contributo',
  `cloud_comp_web_server`DECIMAL(10, 2) COMMENT 'C.3 Cloud Computing - Web Server Contributo',
  `cloud_comp_db_bkup_server`DECIMAL(10, 2) COMMENT 'C.4 Cloud Computing - Database Back Up Contributo',
  `cyber_security`DECIMAL(10, 2) COMMENT 'D. Cyber Security Contributo',
  `approccio_metodologico`TEXT COMMENT 'Descrivere il criterio adottato per la diagnosi digitale, specificando oggetto della valutazione (es. strutture o processi), aspetti osservati (es. tempi, efficacia) e modalità di giudizio (qualitativo, quantitativo, ecc.). L approccio scelto deve essere coerente tra analisi ex-ante ed ex-post e supportare la definizione di obiettivi attesi in termini di benefici. Argomentare eventuali previsioni di costi e benefici con assunzioni motivate e riferimenti comparabili',
  `settore_industriale`TEXT COMMENT 'Settore industriale di riferimento. Descrivere in questo campo lo specifico settore di riferimento.',
  `dimensioni_ambizioni`TEXT COMMENT 'Dimensioni attuali e ambizioni di crescita dell azienda. Descrivere in questo campo le dimensioni e le ambizioni di crescita dell azienda',
  `caratteristiche_prodotti`TEXT COMMENT 'Caratteristiche dei prodotti e o servizi forniti (per esempio turistici, artigianali, tecnici) Descrivere in questo campo le caratteristiche dei prodotti e o servizi offerti dall azienda',
  `maturita_digitale`TEXT COMMENT 'Maturità digitale dell impresa. Descrivere in questo campo il giudizio sintetico che rappresenti complessivamente il grado di maturità digitale dell impresa evidenziandone punti di forza, di debolezza, le possibili opportunutà che si possono prospettare e le minacce da affrontare.',
  `obiettivi_azienda`TEXT COMMENT 'Obiettivi dell azienda (per esempio: crescita presenza sul mercato, efficienza operativa, espansione geografica). Descrivere in questo campo gli obiettivi di business che l azienda intende perseguire attraverso il progetto di digitalizzazione cloud',
  `capacita_investimento`TEXT COMMENT 'Descrivere in questo campo la capacità di investimento dell azienda',
  `capacita_gestionale`TEXT COMMENT 'Descrivere in questo campo la capacità gestionale della trasformazione digitale dell azienda',
  `software_produttivita`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante: Software di produttività personale (es. suite Office, GSuite, ecc.) inclusivi di e-mail aziendali integrate nel flusso di lavoro. Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di software utilizzato.',
  `software_altri`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante:Altri software di utilizzo personale quali antivirus personali o software di utilità di sistema Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di software utilizzato',
  `software_comunicazione`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante:Software di comunicazione, collaborazione e video conferenze. Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di software utilizzato',
  `software_archiviazione`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante:Software per l archiviazione e la gestione documentale in cloud. Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di software utilizzato',
  `software_automazione`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante:Software per l automazione dei flussi di lavoro documentali (es. software per la creazione dei processi di approvazione/revisione/pubblicazione documentale automatizzato, anche di carattere specifico per il settore merceologico). Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di software utilizzato',
  `piattaforme_condivisione`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante:Piattaforme per la condivisione e la distribuzione dei contenuti interni. Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di piattaforma utilizzata',
  `software_firma`TEXT COMMENT 'Descrivere in questo campo la specifica caratteristica allo stato ex-ante:Software di firma digitale e di archiviazione a norma di legge. Indicare il numero di postazioni di lavoro digitali che posseggono applicazioni che rientrano in questa categoria e la tipologia di software utilizzato',
  `piattaforma_dig_commerce`TEXT COMMENT 'Piattaforme integrate di digital commerce comprensive di eventuali applicazioni addizionali. Tali piattaforme possono includere anche funzionalità di integrazione con i punti vendita (es. Click-and-collect) e altre simili modalità di integrazione tra acquisti in presenza e acquisti online',
  `piattaforma_campagne`TEXT COMMENT 'Piattaforme per gestione di campagne pubblicitarie/promozionali sui canali digitali (Digital Marketing) che possano comprendere promozione e ottimizzazione su motori di ricerca generali o settoriali, campagne e-mail, Social, Ads personalizzate',
  `piattaforma_dig_exper`TEXT COMMENT 'Piattaforme di Digital Experience (gestione contenuti web e personalizzazione) ai fini della condivisione di informazioni, servizi e supporto ai clienti / partner',
  `piattaforma_analytics`TEXT COMMENT 'Piattaforme di Analytics a supporto dell analisi del digital commerce ed engagement',
  `piattaforma_mobile`TEXT COMMENT 'Piattaforme di supporto e gestione clienti personalizzate via Web, Mobile App, Social',
  `piattaforma_integrazione`TEXT COMMENT 'Integrazione con piattaforme di terze parti (portali eCommerce o verticali disegmento)',
  `piattaforma_logistica`TEXT COMMENT 'Integrazione con provider di logistica e distribuzione per il miglioramento del tracciamento ed efficacia della distribuzione',
  `presenza_cloud`TEXT COMMENT 'Presenza di applicazioni erogate già in cloud ovvero basate su IaaS, PaaS, o SaaS',
  `applicazioni_client`TEXT COMMENT 'Presenza applicazioni “Client”, ovvero esclusivamente eseguite su dispositivi individuali e di produttività personale',
  `servizi_calcolo`TEXT COMMENT 'Servizi di Calcolo',
  `servizi_db_e_archiv`TEXT COMMENT 'Servizi di Archiviazione e Database',
  `servizi_network`TEXT COMMENT 'Servizi di Rete',
  `servizi_identita_sec`TEXT COMMENT 'Servizi di gestione identità e sicurezza',
  `servizi_devel_test`TEXT COMMENT 'Servizi di strumenti di sviluppo e test',
  `sistemi_accessi`TEXT COMMENT 'Sistemi e servizi per la gestione delle identità e degli accessi',
  `sistemi_network_secur`TEXT COMMENT 'Sistemi e servizi per sicurezza della rete aziendale',
  `sistemi_endpoint_secur`TEXT COMMENT 'Sistemi e servizi per la sicurezza degli endpoint',
  `sistemi_data_secur`TEXT COMMENT 'Sistemi e servizi per la sicurezza dei dati',
  `sistemi_vulnerab_admin`TEXT COMMENT 'Sistemi e servizi per la gestione delle vulnerabilità',
  `sistemi_secur_analytics`TEXT COMMENT 'Sistemi e servizi di Security Analytics',
  `sistemi_applic_security`TEXT COMMENT 'Sistemi e servizi per application security',
  `sistemi_risk_compl_admin`TEXT COMMENT 'Sistemi e servizi per la gestione del rischio e della compliance',
  `sintesi_d_workplace` TEXT COMMENT 'Digital Workplace. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare il numero esatto di postazioni che necessitano una sostituzione e il numero delle postazione che necessitano un upgrade',
  `sintesi_d_comm_engagem`TEXT COMMENT 'Digital Commerce and Engagement. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare il numero esatto di interventi Digital Commerce & Engagement previsti',
  `sintesi_cc_app_server`TEXT COMMENT 'Cloud Computing - Application Server. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Application Server',
  `sintesi_cc_db_server`TEXT COMMENT 'Cloud Computing - Database. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Database Server',
  `sintesi_cc_web_server`TEXT COMMENT 'Cloud Computing - Web Server. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Web Server',
  `sintesi_cc_db_backup`TEXT COMMENT 'Cloud Computing - Database Back Up. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Database Back up',
  `sintesi_cyber_security`TEXT COMMENT 'Cyber Security. Descrivere sinteticamente l esito della valutazione ex-ante eseguita su questo ambito di intervento. Indicare se l Azienda necessita o no di un intervento in cyber security e se si di quale o di quali',
  `impatto_stimato`TEXT COMMENT 'Descrivere sinteticamente l esito della valutazione ex-ante eseguita evidenziando l impatto stimato in termini di: Miglioramento / crescita del fatturato aziendale; Miglioramento dei costi operativi aziendali e Riduzione dei rischi operativi aziendali.',
  `rischi_iniziative`TEXT COMMENT 'Descrivere quali rischi derivino dall attuazione degli interventi (se individuati)',
  `criteri_chiave`TEXT COMMENT 'Descrivere gli elementi chiave da osservare per assicurare il completamento delle iniziative.',
  `priorita `TEXT COMMENT 'Rispetto agli interventi individuati nella sezione precedente, in questo campo è necessario individuare l ordine di avvio per priorità di intervento delle azioni suggerite. Tale sintesi deve evidenziare le dipendenze esistenti fra le iniziative, la capacità/disponibilità di risorse economiche ed umane richieste, la disponibilità di soluzioni/partner tecnologici nell avviare le attività di trasformazione',
  `tempo_completamento`TEXT COMMENT 'Indicare il numero dei mesi previsti',
  `cronoprogramma`TEXT COMMENT 'Rappresentare, anche con ausilio di strumenti grafici (es. GANTT), le azioni/interventi suggeriti rispetto ai tempi di realizzazione previsti',
  `ex_p_sintesi_d_workplace` TEXT COMMENT 'Digital Workplace. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare il numero esatto di postazioni che necessitano una sostituzione e il numero delle postazione che necessitano un upgrade',
  `ex_p_sintesi_d_comm_engagem` TEXT COMMENT 'Digital Commerce and Engagement. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare il numero esatto di interventi Digital Commerce & Engagement previsti',
  `ex_p_sintesi_cc_app_server` TEXT COMMENT 'Cloud Computing - Application Server. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Application Server',
  `ex_p_sintesi_cc_db_server` TEXT COMMENT 'Cloud Computing - Database. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Database Server',
  `ex_p_sintesi_cc_web_server` TEXT COMMENT 'Cloud Computing - Web Server. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Web Server',
  `ex_p_sintesi_cc_db_backup` TEXT COMMENT 'Cloud Computing - Database Back Up. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare se l Azienda necessiti (o no) di acquistare (o migrare verso) una VM - Database Back up',
  `ex_p_sintesi_cyber_security` TEXT COMMENT 'Cyber Security. Descrivere sinteticamente l esito della valutazione ex-post eseguita su questo ambito di intervento. Indicare se l Azienda necessita o no di un intervento in cyber security e se si di quale o di quali',
  `ex_p_v_f_d_workplace` BOOLEAN COMMENT 'A. Digital Workplace',
  `ex_p_v_f_d_comm_engagem` BOOLEAN COMMENT 'B. Digital Commerce and Engagement',
  `ex_p_v_f_cloud_computing` BOOLEAN COMMENT 'C. Cloud Computing',
  `ex_p_v_f_cyber_security` BOOLEAN COMMENT 'D. Cyber Security',
  `ex_p_giudizio_finale` TEXT COMMENT 'Descrivere EX-POST l esito conclusivo della Diagnosi Digitale condotta in seguito alla realizzazione del gli interventi'
  `date_creation` datetime DEFAULT current_timestamp(),
  `tms` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `fk_user_author` int(11) DEFAULT NULL,
  `fk_user_modif` int(11) DEFAULT NULL,
  `datec` datetime DEFAULT current_timestamp(),
  `model_pdf` varchar(255) DEFAULT NULL,
  `oggetto_valutazione_ai` text DEFAULT NULL,
  PRIMARY KEY (`rowid`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;